### ISSUE TITLE
Missing required parameter: '<heapfile>'

### ISSUE THREAD

**Issue by SummerSec** [whwlsfb/JDumpSpider#2]
heapfile 是什么？如何获取？

**Comment by whwlsfb** [comment]
heapdump一般是来源于各个框架的heapdump接口（例如spring框架的actuator/heapdump），需要将dump下载到本地，再使用本工具提取信息。

**Comment by SummerSec** [comment]
> heapdump一般是来源于各个框架的heapdump接口（例如spring框架的actuator/heapdump），需要将dump下载到本地，再使用本工具提取信息。

哪有没有工具直接能dump呢？

**Comment by SummerSec** [comment]
dump运行中的应用程序

**Comment by whwlsfb** [comment]
可以尝试使用命令
```
jmap -dump:live,format=b,file=/path/to/heapfile.hprof <PID>
```

**Comment by SummerSec** [comment]
> 可以尝试使用命令
> 
> ```
> jmap -dump:live,format=b,file=/path/to/heapfile.hprof <PID>
> ```

ok,thanks
