### ISSUE TITLE
github actions build

### ISSUE THREAD

**Issue by qianniaoge** [whwlsfb/JDumpSpider#3]

**Comment by qianniaoge** [comment]
name: Java CI

on:
  watch:
    types: started
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mkdir release && cp target/*.jar release
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: JDumpSpider
          # Directory containing files to upload
          path: release

**Comment by whwlsfb** [comment]
感谢提供CI脚本👌
