### ISSUE TITLE
ShiroKey获取失败

### ISSUE THREAD

**Issue by Asura88** [whwlsfb/JDumpSpider#4]
ShiroKey
CookieRememberMeManager

获取失败

不仅仅失败，甚至命令行都没有弹出提示获取shirokey

**Comment by whwlsfb** [comment]
支持ShiroKey提取的版本目前尚未上传至Release里，请确认是否是通过拉取master分支代码编译的？

**Comment by Asura88** [comment]
哦，我是下载你编制好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 晚上11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [whwlsfb/JDumpSpider] ShiroKey获取失败 (Issue #4)




 
支持ShiroKey提取的版本目前尚未上传至Release里，请确认是否是通过拉取master分支代码编译的？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
