### ISSUE TITLE
OSS报错

### ISSUE THREAD

**Issue by fengchenzxc** [whwlsfb/JDumpSpider#5]
oss运行报错，应该是首行多了一个括号
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/41096522/177249609-8d68ea3a-01d4-42fb-a850-6ad09befca72.png">
然后把括号去了后，报错类型转换问题
org.graalvm.visualvm.lib.profiler.oql.engine.api.OQLException: java.lang.ClassCastException: jdk.nashorn.internal.runtime.Undefined cannot be cast to java.lang.String

**Comment by whwlsfb** [comment]
收到，感谢，将在后续解决

**Comment by Asura88** [comment]
马上hw了，什么时候更新新版本呢？

**Comment by whwlsfb** [comment]
已更新，请复现下问题，确认是否正常

**Comment by Asura88** [comment]
正常，可以关闭了
